# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "adapting_2d_vits_for_3d_point_clouds"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]